name: Chersak Kingkan
# Site settings
title: Chersak Kingkan blog
email: 
description: ""
baseurl: ""
url: "http://ckingkan.github.io"
github_username:  ckingkan

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
permalink: /blog/:year/:month/:day/:title

theme: jekyll-theme-architect